import type { GenerateInput } from "../types.js";

function subscriberPatterns(namespace: string): string[] {
  const patterns = [".+/cmd_vel", "cmd_vel"];
  const ns = namespace.replace(/^\/+|\/+$/g, "");
  if (ns) patterns.push(`${ns}/cmd_vel`);
  return patterns;
}

export function renderBridge(input: GenerateInput): string {
  const isolationPublic = input.identity.isolation === "public";
  const endpoints = input.identity.hubEndpoints;
  const connect =
    endpoints.length > 0
      ? `  connect: {
    endpoints: ${JSON.stringify(endpoints)},
  },`
      : `  // Public LAN: multicast scouting finds the hub. Add connect.endpoints if this box cannot scout.
  connect: {
    endpoints: [],
  },`;

  const subs = subscriberPatterns(input.robotNamespace)
    .map((p) => JSON.stringify(p))
    .join(", ");

  return `// CONFIG FOR: zenoh-bridge-ros2dds (standalone) ON THE ROBOT
// DO NOT use this file with zenohd. zenohd does not load the ros2dds plugin and will
// panic on unknown keys (e.g. "allow"). On the hub, run zenohd with zenohd.json5 only.
//
// On the robot: zenoh-bridge-ros2dds -c zenoh-bridge-ros2dds-robot.json5
// Generated by @agenticros/zenoh-fleet for fleet "${input.identity.name}".

{
  mode: "client",
${connect}
  scouting: {
    multicast: {
      enabled: ${isolationPublic},
    },
  },
  plugins: {
    ros2dds: {
      allow: {
        publishers: [".+"],
        subscribers: [${subs}],
        service_servers: [],
        service_clients: [],
        action_servers: [],
        action_clients: [],
      },
    },
  },
}
`;
}
