import type { GenerateInput } from "../types.js";

export function renderRmwSession(input: GenerateInput): string {
  const isolationPublic = input.identity.isolation === "public";
  const endpoints = input.identity.hubEndpoints;
  const connect =
    endpoints.length > 0
      ? `  connect: {
    endpoints: ${JSON.stringify(endpoints)},
  },`
      : `  connect: {
    endpoints: [],
  },`;

  return `// CONFIG FOR: rmw_zenoh session (ROS 2 client to the fleet hub)
// Set ZENOH_SESSION_CONFIG_URI to this file (or merge into your rmw_zenoh session config).
// Generated by @agenticros/zenoh-fleet for fleet "${input.identity.name}".

{
  mode: "client",
${connect}
  scouting: {
    multicast: {
      enabled: ${isolationPublic},
    },
  },
}
`;
}
