import type { GenerateInput } from "../types.js";

function scoutingBlock(enabled: boolean, indent = "  "): string {
  return `${indent}scouting: {
${indent}  multicast: {
${indent}    enabled: ${enabled},
${indent}  },
${indent}},`;
}

export function renderZenohd(input: GenerateInput): string {
  const isolationPublic = input.identity.isolation === "public";
  const remoteApi = input.integrations.agenticros
    ? `
  plugins_loading: {
    enabled: true,
    search_dirs: ["~/.zenoh/lib", "/opt/homebrew/lib", "/usr/local/lib"],
  },
  plugins: {
    remote_api: {
      websocket_port: "${input.identity.wsPort}",
    },
  },`
    : "";

  return `// CONFIG FOR: zenohd (router / hub)
// Generated by @agenticros/zenoh-fleet for fleet "${input.identity.name}".
// Do not copy Eclipse DEFAULT_CONFIG.json5 — this file is the listen + plugin surface only.

{
  mode: "router",
  listen: {
    endpoints: ["${input.listenEndpoint}"],
  },
${scoutingBlock(isolationPublic)}
${remoteApi}
}
`.replace(/\n\n\n+/g, "\n\n");
}
