import { resolve } from "node:path";

import { corebrumTcpUrl, hostFromEndpoint } from "./detect.js";
import type { GenerateInput } from "./types.js";

function hubHost(input: GenerateInput): string | null {
  return (
    hostFromEndpoint(input.identity.hubEndpoints[0]) ??
    hostFromEndpoint(input.identity.wsEndpoint) ??
    input.advertisedIp
  );
}

/** Absolute POSIX path for copy-pasteable shell commands. */
export function configPath(outDir: string | undefined, file: string): string {
  const dir = resolve(!outDir || outDir === "." || outDir === "./" ? "." : outDir);
  return `${dir.replace(/\\/g, "/")}/${file}`;
}

export function renderNextSteps(input: GenerateInput, outDir: string): string {
  const lines = ["Next (absolute path; works from any directory):", ""];
  if (input.role === "hub") {
    lines.push("```bash");
    lines.push(`zenohd -c ${configPath(outDir, "zenohd.json5")}`);
    lines.push("```");
  } else if (input.integrations.ros2ddsBridge) {
    lines.push("```bash");
    lines.push(
      `zenoh-bridge-ros2dds -c ${configPath(outDir, "zenoh-bridge-ros2dds-robot.json5")}`,
    );
    lines.push("```");
  } else {
    lines.push(`See ${configPath(outDir, "README.md")} for role-specific commands.`);
  }
  lines.push("");
  return lines.join("\n");
}

export function renderDeployReadme(input: GenerateInput): string {
  const lines: string[] = [];
  const host = hubHost(input);
  const tcp = input.identity.tcpPort;
  const ws = input.identity.wsPort;
  const name = input.identity.name;
  const privateMesh = input.identity.isolation === "private";

  lines.push(`# ${name} (${input.role})`);
  lines.push("");
  lines.push(
    `Generated by \`@agenticros/zenoh-fleet\`. Isolation: **${input.identity.isolation === "public" ? "public LAN" : "private mesh"}**.`,
  );
  lines.push("");

  if (input.role === "hub") {
    lines.push("## Run the hub router");
    lines.push("");
    lines.push("From **this directory** (the folder that contains `zenohd.json5`):");
    lines.push("");
    lines.push("```bash");
    lines.push("zenohd -c zenohd.json5");
    lines.push("```");
    lines.push("");
    lines.push(
      "If you are still in the parent directory, use `zenohd -c <this-folder>/zenohd.json5` instead.",
    );
    lines.push("");
    if (input.integrations.agenticros) {
      lines.push(
        "Install `zenoh-plugin-remote-api` so AgenticROS can connect over WebSocket (not TCP).",
      );
      lines.push("");
      lines.push("```bash");
      lines.push("brew tap eclipse-zenoh/homebrew-zenoh");
      lines.push("brew install zenoh zenoh-plugin-remote-api");
      lines.push("```");
      lines.push("");
    }
    if (host) {
      lines.push(`Advertised TCP: \`tcp/${host}:${tcp}\``);
      if (input.integrations.agenticros) {
        lines.push(`Advertised WebSocket: \`ws://${host}:${ws}\``);
      }
      lines.push("");
    } else {
      lines.push(
        "No advertised LAN IP was detected. Members on other hosts cannot use `127.0.0.1`. Re-run with `--hub-ip <lan-ip>` or pass a reachable VPN address.",
      );
      lines.push("");
    }
  } else {
    lines.push("## This machine is a member (client)");
    lines.push("");
    lines.push("Do **not** run a second `zenohd` here. Connect to the hub.");
    lines.push("");
    if (input.integrations.ros2ddsBridge) {
      lines.push("### Robot (zenoh-bridge-ros2dds)");
      lines.push("");
      lines.push("From **this directory**:");
      lines.push("");
      lines.push("```bash");
      lines.push("zenoh-bridge-ros2dds -c zenoh-bridge-ros2dds-robot.json5");
      lines.push("```");
      lines.push("");
      if (host) {
        lines.push("Check the hub is reachable:");
        lines.push("");
        lines.push("```bash");
        lines.push(`nc -zv ${host} ${tcp}`);
        lines.push("```");
        lines.push("");
      }
    }
    if (input.integrations.agenticros) {
      const wsEp = input.identity.wsEndpoint ?? (host ? `ws://${host}:${ws}` : "ws://<hub-ip>:10000");
      lines.push("### AgenticROS");
      lines.push("");
      lines.push(
        `Set **Zenoh Router Endpoint** to \`${wsEp}\` (WebSocket, never \`tcp/...\`).`,
      );
      lines.push("");
      lines.push("```bash");
      lines.push(`./scripts/configure_agenticros.sh --mode zenoh --zenoh-endpoint ${wsEp}`);
      lines.push("```");
      lines.push("");
    }
    if (input.integrations.corebrum) {
      const url = host ? corebrumTcpUrl(host, tcp) : `tcp://<hub-ip>:${tcp}`;
      lines.push("### Corebrum");
      lines.push("");
      lines.push("```bash");
      lines.push(`corebrum daemon --zenoh-router ${url}`);
      lines.push("```");
      lines.push("");
    }
    if (input.integrations.rmwZenoh) {
      lines.push("### rmw_zenoh");
      lines.push("");
      lines.push("Point `ZENOH_SESSION_CONFIG_URI` at `rmw-zenoh-session.json5`.");
      lines.push("");
    }
  }

  if (privateMesh) {
    lines.push("## Private mesh");
    lines.push("");
    lines.push(
      "Multicast scouting is off. If the hub IP is unreachable from this machine, the node will not join. Cross-site setups need a VPN (e.g. Tailscale) or a public hub — ARC only distributes the address the hub claimed.",
    );
    lines.push("");
  }

  lines.push("## Other machines");
  lines.push("");
  lines.push("Each box runs this CLI independently and picks **hub** or **member**:");
  lines.push("");
  lines.push("```bash");
  lines.push("npx @agenticros/zenoh-fleet");
  lines.push("```");
  lines.push("");
  lines.push("Or join from this directory's `fleet.json`:");
  lines.push("");
  lines.push("```bash");
  lines.push(`npx @agenticros/zenoh-fleet init --role member --name ${name} --join ./fleet.json`);
  lines.push("```");
  lines.push("");
  lines.push(
    "If the hub published to AgenticROS Cloud (ARC): log in (`agenticros login`) on the other machine, then run `npx @agenticros/zenoh-fleet` and accept the defaults.",
  );
  lines.push("");

  return lines.join("\n");
}

export function printDeploy(input: GenerateInput, outDir: string): void {
  process.stdout.write(renderNextSteps(input, outDir));
  process.stdout.write(renderDeployReadme(input));
}
